# Generated by Django 4.2.16 on 2024-12-18 16:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0031_alter_vendor_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='vendor_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='password123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(default='password123', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
